name: Use App token
description: Run GitHub Actions as a GitHub App by using the app's authentication token.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  app_id:
    description: The ID of the GitHub App.
    required: false
  private_key:
    description: The private key of the GitHub App (can be Base64 encoded).
    required: false
  fallback:
    description: The fallback token when bot token generate failed.
    required: false
  app_slug_name:
    description: The app slug name exported to `env` or saved to `secrets`.
    required: false
    default: BOT_NAME
  app_token_name:
    description: The app token name exported to `env` or saved to `secrets`.
    required: false
    default: BOT_TOKEN
  secret:
    description: Specify true to save app token and app slug into the secrets of current repository.
    required: false
    default: false
  target-organization:
    description: The organization to get the installation token about
    required: false
  clean:
    description: Specify true to clean saved secrets when workflow run completed.
    required: false
    default: true

outputs:
  bot_name:
    description: The name of the GitHub App on the current repository.
  bot_token:
    description: The token of the GitHub App on the current repository.

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js

branding:
  icon: anchor
  color: orange # gray-dark purple red orange green blue yellow black white
